/* automatically generated by rust-bindgen 0.72.1 */

pub const PluginStringKind_PLUGIN_STRING_STATIC: PluginStringKind = 0;
pub const PluginStringKind_PLUGIN_STRING_OWNED: PluginStringKind = 1;
#[doc = " String lifetimes"]
pub type PluginStringKind = ::std::os::raw::c_uint;
#[doc = " A string with a static or dynamic lifetime"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PluginString {
    pub data: *mut ::std::os::raw::c_char,
    pub kind: PluginStringKind,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PluginString"][::std::mem::size_of::<PluginString>() - 16usize];
    ["Alignment of PluginString"][::std::mem::align_of::<PluginString>() - 8usize];
    ["Offset of field: PluginString::data"][::std::mem::offset_of!(PluginString, data) - 0usize];
    ["Offset of field: PluginString::kind"][::std::mem::offset_of!(PluginString, kind) - 8usize];
};
#[doc = " Pointer to functions being exported"]
pub type PluginFn = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const ::std::os::raw::c_char) -> PluginString,
>;
pub type PluginFreeFn = ::std::option::Option<unsafe extern "C" fn(str_: PluginString)>;
#[doc = " Here name can be anything as long as the function pointer is valid.\n Name should be used as an alias to the function as its what CC will call it"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PluginFunction {
    pub name: *const ::std::os::raw::c_char,
    pub function: PluginFn,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PluginFunction"][::std::mem::size_of::<PluginFunction>() - 16usize];
    ["Alignment of PluginFunction"][::std::mem::align_of::<PluginFunction>() - 8usize];
    ["Offset of field: PluginFunction::name"]
        [::std::mem::offset_of!(PluginFunction, name) - 0usize];
    ["Offset of field: PluginFunction::function"]
        [::std::mem::offset_of!(PluginFunction, function) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PluginInfo {
    #[doc = " The name given to this plugin to be referenced by CC"]
    pub plugin_name: *mut ::std::os::raw::c_char,
    #[doc = " Version used for debug information"]
    pub version: ::std::os::raw::c_uint,
    #[doc = " Number of elements in `fns`"]
    pub fn_count: ::std::os::raw::c_ulong,
    #[doc = " Function call table"]
    pub fns: *mut PluginFunction,
    pub string_free: PluginFreeFn,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of PluginInfo"][::std::mem::size_of::<PluginInfo>() - 40usize];
    ["Alignment of PluginInfo"][::std::mem::align_of::<PluginInfo>() - 8usize];
    ["Offset of field: PluginInfo::plugin_name"]
        [::std::mem::offset_of!(PluginInfo, plugin_name) - 0usize];
    ["Offset of field: PluginInfo::version"][::std::mem::offset_of!(PluginInfo, version) - 8usize];
    ["Offset of field: PluginInfo::fn_count"]
        [::std::mem::offset_of!(PluginInfo, fn_count) - 16usize];
    ["Offset of field: PluginInfo::fns"][::std::mem::offset_of!(PluginInfo, fns) - 24usize];
    ["Offset of field: PluginInfo::string_free"]
        [::std::mem::offset_of!(PluginInfo, string_free) - 32usize];
};
#[doc = " Plugin entrypoint"]
pub type plg_endpoints = ::std::option::Option<unsafe extern "C" fn() -> *const PluginInfo>;
